env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
"parser": "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2016
  sourceType: module
plugins:
  - react
  - import
rules: {
  no-var: "error",
  "react/jsx-max-props-per-line": [2, { "maximum": 1, "when": "multiline" }],
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
  "react/jsx-indent" : ["error", 4],
  "react/prop-types": [0, { ignore: [], customValidators: [], skipUndeclared: true }],
  "react/destructuring-assignment": [0, 'always']
}
